In [1]:
from pulp import *
import numpy as np
import itertools
from collections import deque
import numpy as np

In [3]:
# Create the model
m = LpProblem(name="test", sense=LpMinimize)

real_table = [[2,3,5],[2,3,5],[4,6,10]]
pert_table = [[0,1,-1],[-1,1,0],[1,1,-1]]
out_table = np.add(real_table,pert_table)

i_max = len(out_table) - 1
j_max = len(out_table) - 1

# Initialize the decision variables
x = np.array([[LpVariable(name=f"x_{i}_{j}", cat='Integer') 
               for i in range(i_max + 1)] for j in range(j_max +1)])

# Add the constraints to the model
for i in range(i_max+1):
    for j in range(j_max+1):
        m += x[i][j] <= out_table[i][j] +1
        m += x[i][j] >= out_table[i][j] -1
        
for i in range(i_max+1):
    m += lpSum(x[i,:][0:j_max]) == x[i][j_max]
    
for j in range(j_max+1):
    m += lpSum(x[:,j][0:i_max]) == x[i_max][j]
    
    
# Add the objective function to the model

m += 0

# Solve the problem
status = m.solve()

out_x = np.zeros_like(x)
for i in range(len(x)):
    for j in range(len(x[0])):
        out_x[i][j] = x[i][j].value()
print(out_x)

# print(f"status: {m.status}, {LpStatus[m.status]}")
# print(f"objective: {m.objective.value()}")
# for var in m.variables():
#     print(f"{var.name}: {var.value()}")
    
# for name, constraint in m.constraints.items():
#     print(f"{name}: {constraint.value()}")

[[2.0 3.0 5.0]
 [2.0 3.0 5.0]
 [4.0 6.0 10.0]]
